[versions]
jackson = "2.18.0"
retrofit2 = "2.11.0"
slf4j = "2.0.16"
errorprone = "2.33.0"

[libraries]
errorprone_annotations = { module = "com.google.errorprone:error_prone_annotations", version.ref = "errorprone" }
errorprone_core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone" }

jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind",  version.ref = "jackson" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit2" }
retrofit-converter-jackson = { module = "com.squareup.retrofit2:converter-jackson", version.ref = "retrofit2" }
retrofit-converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofit2" }

junit = "junit:junit:4.13.2"
mockito-core = "org.mockito:mockito-core:5.14.1"

slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-reload4j = { module = "org.slf4j:slf4j-reload4j", version.ref = "slf4j" }

[bundles]
retrofit = ["retrofit", "retrofit-converter-jackson", "retrofit-converter-scalars" ]

[plugins]
versions = "com.github.ben-manes.versions:0.51.0"
errorprone = "net.ltgt.errorprone:4.0.1"

