[versions]
retrofit2 = "2.9.0"
slf4j = "2.0.7"

[libraries]
jackson-databind = "com.fasterxml.jackson.core:jackson-databind:2.14.2"
spotbugs = "com.github.spotbugs:spotbugs:4.7.3"

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit2" }
retrofit-converter-jackson = { module = "com.squareup.retrofit2:converter-jackson", version.ref = "retrofit2" }
retrofit-converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofit2" }

junit = "junit:junit:4.13.2"
#org-apache-logging-log4j-log4j-core = "org.apache.logging.log4j:log4j-core:2.17.1"
mockito-core = "org.mockito:mockito-core:5.2.0"

slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-reload4j = { module = "org.slf4j:slf4j-reload4j", version.ref = "slf4j" }

[bundles]
retrofit = ["retrofit", "retrofit-converter-jackson", "retrofit-converter-scalars" ]

[plugins]
versions = "com.github.ben-manes.versions:0.46.0"
spotbugs = "com.github.spotbugs:5.0.14"
version-catalog-update = "nl.littlerobots.version-catalog-update:0.8.0"

